services:
  paperless-broker:
    image: docker.io/library/redis:8
    container_name: paperless-broker
    restart: unless-stopped
    networks:
      - paperless-internal-bridge
    volumes:
      - ./paperless_redisdata:/data

  paperless-db:
    image: docker.io/library/postgres:18
    container_name: paperless-database
    restart: unless-stopped
    volumes:
      - ./paperless_pgdata:/var/lib/postgresql
    networks:
      - paperless-internal-bridge
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webui
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-broker
    expose:
      - "8000"
    networks:
      - caddy-internal-bridge
      - paperless-internal-bridge
    volumes:
      - ./paperless_data:/usr/src/paperless/data
      - ./paperless_media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file:
      - .env
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "OAUTH_PKCE_ENABLED": true,
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "authentik",
                "client_id": "dD9u0FCut6NQZloQoYbubVzzB1qcT6sKn573GFzk",
                "secret": "2Q2PbXu4fibDuECNcJyQ4mrUt9lt0D1Ze2SESbKuJF530hiaM2dtsQBdeNognxYe5FA1KlN5TzTg75OTCgPPvWdf0BCteAbPaxacsLVIRdk5NKYxcRWSSWqlftTF8Yo1",
                "settings": {
                  "server_url": "https://idp.digisign.qzz.io/application/o/paperless/.well-known/openid-configuration",
                  "fetch_userinfo": true
                }
              }
            ],
            "SCOPE": ["openid", "profile", "email"]
          }
        }
      PAPERLESS_LOGOUT_REDIRECT_URL: "https://idp.digisign.qzz.io/application/o/paperless/end-session/"
      PAPERLESS_SOCIAL_AUTO_SIGNUP: true
      PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: false
      PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: true
      PAPERLESS_DISABLE_REGULAR_LOGIN: false
      PAPERLESS_REDIRECT_LOGIN_TO_SSO: false

    # ===== DOCKER RESOURCE LIMITS =====
    # 6 CPU cores ensures massive OCR speed, but leaves 14 cores for the host.
    cpus: "12.0"
    
    # 6GB RAM cap. OCR with Tesseract can spike to 2-4GB on large PDFs. 
    # 6GB guarantees it never crashes your host.
    mem_limit: 8144M
    
    # Soft reservation: keeps 2GB set aside for it even under host memory pressure.
    mem_reservation: 2048M


networks:
  paperless-internal-bridge:
    driver: bridge
