services:
  wordpress_db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./wordpress_db_data:/var/lib/mysql
    networks:
      - wordpress-internal-bridge

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    container_name: wordpress_site
    restart: unless-stopped
    expose:
      - "80"
    #ports:
    #  - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - wordpress-internal-bridge
      - caddy-internal-bridge # To be accessible via Caddy reverse proxy

  wordpress_phpmyadmin:
    depends_on:
      - wordpress_db
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordpress_phpmyadmin
    restart: unless-stopped
    expose:
      - "80"
    #ports:
    #  - "${PMA_PORT}:80"
    environment:
      PMA_HOST: wordpress_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - wordpress-internal-bridge
      - caddy-internal-bridge # To be accessible via Caddy reverse proxy

#volumes:
#  wordpress_db_data:
#  wp_data:

networks:
  wordpress-internal-bridge:
    driver: bridge